services:
  - type: web
    name: backend-link
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api/v1
